### ISSUE TITLE
Email groups

### ISSUE THREAD

**Issue by jrera** [bwya77/Master-User-Creator#10]
Hello,

When creating a new user and I select "Mail Groups" they never seem to apply and I have to go in and manually add them

**Comment by bwya77** [comment]
Hello - I have tested Mail Groups with creating a disabled and regular Office 365 user and it is properly adding the user to the groups selected. 

For Mail Groups your user must have a license that provides them an Exchange Mailbox which may be what you're running into.

If you have more information please feel free to comment and re-open
