### ISSUE TITLE
Type ahead searching for AD Groups/attributes

### ISSUE THREAD

**Issue by dfousy** [bwya77/Master-User-Creator#14]
In an organization with many AD groups, type ahead would be great so groups could be searched and filtered in real time to narrow results. For instance, if I needed to add a user to 3 groups that begin with EastCoast_xxxxxx I could type "EastCoast" and see only groups that contain or begin with that string.

As I was thinking about this, the same would be awesome for user attributes as well. Not to necessarily enumerate all of them on the form at once, but type into a search field for "msRTCSIP-AcpInfo" and generate a field to edit that attribute? Perhaps there is a better way to do that...

**Comment by bwya77** [comment]
got it working :) itll be in next version 1.0.6

**Comment by bwya77** [comment]
Fixed in next version (v2 instead of 1.0.6)
