### ISSUE TITLE
Specify OUs for Groups

### ISSUE THREAD

**Issue by nswetland** [bwya77/Master-User-Creator#20]
It seems that when modifying group membership, it will find AD Groups nested in OUs under the root "Groups" OU, but will not allow modification of the memberships of any group below the root Group folder... 
e.g. `OU=Office365,OU=XYZCompany Groups,DC=domain,DC=XYZ,DC=com`

The groups thing spits out an error:
`[14:40:11] - WARN: Cannot find an object with identity: 'O365-Normal-License' under: 'DC=domain,DC=XYZ Company,DC=com'.   whereas the actual OU is the one from above.`

It might not be correctly walking through the group OUs...  maybe the space in the OU name is causing the issue? 
I dont have PowerShell Studio so I haven't looked at the actual PS code.

Thanks!

**Comment by bwya77** [comment]
thanks, fixed in v2.0.0
