### ISSUE TITLE
Option to disable features such as 'Outlook on the Web' and ActveSync for mobile devices

### ISSUE THREAD

**Issue by cjdrew81** [bwya77/Master-User-Creator#21]
Hi,
Great tool, it definitely saves us a lot of time logging onto the domain controller and then logging into Office 365 to create the new mailbox and assign to groups.
It would be great if there were some additional options to disable some of the mailbox features when setting up the mailbox.
We also would find the multi license assignment very helpful!
Keep up the good work

**Comment by bwya77** [comment]
added disable OWA in v2.0.0
just finished adding multiple licenses in v2.0.0

working on AS now

**Comment by cjdrew81** [comment]
Great!!! Will test it out now ☺

Cheers for responding and thanks again for your hard work.

Chris


   
Chris Drew
Support & VoIP Services Manager
T:0161 235 5344
E:
chris@cloud10.it
W:www.cloud10.it
   
 Cloud10 is an Environmentally Friendly company. Please consider the environment before printing this email
 The information contained in this e-mail is confidential and may be privileged. It is intended for the addressee only. If you are not the intended recipient, please delete this e-mail
 immediately. The contents of this e-mail must not be disclosed or copied without the sender's consent. The statements and opinions expressed in this message are those of the author
 and do not necessarily reflect those of the company. The company does not take any responsibility for the views of the author.

**Comment by bwya77** [comment]
its not compiled yet, if you have powershell studio you can copy the dev branch and test it out

**Comment by bwya77** [comment]
Async is working
