### ISSUE TITLE
Enable Remote Mailbox during hybrid 

### ISSUE THREAD

**Issue by bwya77** [bwya77/Master-User-Creator#28]
What about when there is a hybrid environment? At the moment we have to run the command "Enable-RemoteMailbox" to create a mailbox in Exchange Online for our AD user(once the user has synced of course)

**Comment by thetootall** [comment]
Hybrid is still needed to properly enable mailboxes (with some 20 or so attributes it creates), not to mention management of DLs, proxy addresses, HideFromAddressBook, and more

**Comment by kengeman** [comment]
Is there an ETA for when Enable-RemoteMailbox might get added? 

Enable-RemoteMailbox -identity <user>@mydomain.com -RemoteRoutingAddress <user>@mydomain.onmicrosoft.com
Enable-RemoteMailbox -identity user@mydomain.com -Archive

Those two commands would make the Master User Creator the perfect tool. Thanks!

**Comment by bwya77** [comment]
Added in v2.0.2 that I just pushed
can specify exchange server locally or remote (uses winrm)
can also set in options remote fwding domain
