### ISSUE TITLE
Incorrect GUI scaling in Powershell Studio

### ISSUE THREAD

**Issue by ragingsysadmin** [bwya77/Master-User-Creator#52]
Not exactly sure if this is an issue with Powershell Studio or possibly me not importing the project correctly. When I import the project into the studio, the form sizing gets set to 1105x1090. Of course when I compile this it cuts off on my screen and looks ridiculous.

Before I run through and size everything out again, do you have any pointers?

**Comment by jagannath79** [comment]
Even I am facing the same issue that's reported by ragingsysadmin.
Is there any solution around it. @ragingsysadmin were you able to get any work around for the resolution issue when the project is imported in Powershell Studio ?

@bwya77 can you please help us and guide how to fix the resolution issue when the project is imported in powershell studio.

**Comment by Hlotina** [comment]
Has anyone had any luck with this? Getting a ballooned version when I import to PSS

**Comment by ragingsysadmin** [comment]
@jagannath79 and @Hlotina I have not found any work around to this sadly.

**Comment by bwya77** [comment]
this is because I created the program on a surface book which has a crazy high resolution - I cannot fix this as its because of PS Studio

3240x2160 @150%
