### ISSUE TITLE
Add account expiration

### ISSUE THREAD

**Issue by Girard-Arnold** [bwya77/Master-User-Creator#9]
Could it be possible to add account expiration? I feel this is a missing feature.

**Comment by bwya77** [comment]
Added in v.1.0.2 which is published! 

https://github.com/bwya77/Master-User-Creator/blob/master/README.md#account-disabled

![account_disabled](https://user-images.githubusercontent.com/6300377/42856839-946a0986-8a0c-11e8-9850-3b411448307b.png)
